openapi: 3.0.3
info:
  title: OpenAPI schema for template remote-exec
components:
  schemas:
    variables:
      type: object
      required:
      - connection_host
      properties:
        connection_type:
          title: Connection Type
          type: string
          description: The connection type, valid values are ssh and winrm.
          default: ssh
          enum:
          - ssh
          - winrm
          nullable: true
          x-walrus-ui:
            order: 1
        connection_host:
          title: Connection Host
          type: string
          description: The address of the resource to connect to.
          x-walrus-ui:
            order: 2
        connection_port:
          title: Connection Port
          type: number
          description: The port of the resource to connect to, 22 for type ssh, 5985 for type winrm.
          default: 22
          nullable: true
          x-walrus-ui:
            order: 3
        connection_user:
          title: Connection User
          type: string
          description: The user to use for the connection.
          default: ubuntu
          nullable: true
          x-walrus-ui:
            order: 4
        connection_password:
          title: Connection Password
          type: string
          description: The password to use for the connection.
          default: ""
          format: password
          nullable: true
          writeOnly: true
          x-walrus-ui:
            order: 5
        connection_private_key:
          title: Connection Private Key
          type: string
          description: The contents of an SSH key to use for the connection.
          default: ""
          nullable: true
          writeOnly: true
          x-walrus-ui:
            order: 6
        script_path:
          title: Script Path
          type: string
          description: The scrpit path of the resource for remote execution.
          default: /opt/script.sh
          nullable: true
          x-walrus-ui:
            order: 7
        executed_repeatedly:
          title: Executed Repeatedly
          type: boolean
          description: Allow command to be executed repeatedly.
          default: false
          nullable: true
          x-walrus-ui:
            order: 8
